sudo: required
services:
  - docker

env: SH="docker exec --user cs6290 hpcsesc bash -c"

before_install:
- docker pull markiemark1/6290:precise
- docker run --name hpcsesc -d markiemark1/6290:precise tail -f /dev/null
- docker ps
- $SH "whoami"
- $SH "ls"
- $SH "cd ~/sesc && make"
- $SH "cd ~/sesc/apps/Splash2/lu && make"
- $SH "cd ~/sesc/apps/Splash2/lu && mkdir Ap1 && cp *.mipseb ./Ap1"
- $SH "cd ~/sesc/apps/Splash2/lu && mkdir Ap2 && cp *.mipseb ./Ap2"
- $SH "cd ~/sesc/apps/Splash2/lu && mkdir Ap4 && cp *.mipseb ./Ap4"
- $SH "cd ~/sesc/apps/Splash2/lu && mkdir reports"

script:

- $SH "cd ~/sesc/apps/Splash2/lu/Ap1 && ~/sesc/sesc.opt -fAp1 -c ~/sesc/confs/cmp16-noc.conf -olu.out -elu.err lu.mipseb -n512 -p1 && cp sesc_* ./../reports"
- $SH "cd ~/sesc/apps/Splash2/lu/Ap2 && ~/sesc/sesc.opt -fAp2 -c ~/sesc/confs/cmp16-noc.conf -olu.out -elu.err lu.mipseb -n512 -p2 && cp sesc_* ./../reports"
- $SH "cd ~/sesc/apps/Splash2/lu/Ap4 && ~/sesc/sesc.opt -fAp4 -c ~/sesc/confs/cmp16-noc.conf -olu.out -elu.err lu.mipseb -n512 -p4 && cp sesc_* ./../reports"

- $SH "cd ~/sesc/apps/Splash2/lu/reports && ~/sesc/scripts/report.pl sesc_*"
- docker cp --user cs6290 hpcsesc:/home/cs6290/sesc/lu/reports ./
- docker cp --user cs6290 hpcsesc:/home/cs6290/sesc/lu/Ap1 ./
- docker cp --user cs6290 hpcsesc:/home/cs6290/sesc/lu/Ap2 ./
- docker cp --user cs6290 hpcsesc:/home/cs6290/sesc/lu/Ap4 ./


